language: cpp
compiler:
  - gcc
  - clang
before_install: sudo apt-get update
install:
  - curl -R -O http://www.lua.org/ftp/lua-5.2.3.tar.gz
  - tar zxf lua-5.2.3.tar.gz
  - cd lua-5.2.3
  - make linux
  - sudo make install
  - cd ..
before_script:
  - mkdir build
  - cd build
script:
  - cmake ..
  - make
  - ./test
branches:
  only:
    - master
notifications:
  recipients:
    - jeremycong@gmail.com
  email:
    on_success: change
    on_failure: always