language: cpp
compiler:
  - gcc
  - clang
before_install: sudo apt-get update
install:
  - sudo apt-get install lua5.2 cmake
before_script:
  - mkdir build
  - cd build
script:
  - cmake ..
  - make
  - ./test
branches:
  only:
    - master
notifications:
  recipients:
    - jeremycong@gmail.com
  email:
    on_success: change
    on_failure: always